core/urls.py
from django.urls import path
from .views import home, CheckoutView, ItemDetailView, add_to_cart, remove_from_cart, OrderSummaryView,  remove_single_item_from_cart, PaymentView, AddCouponView, category_profile

app_name="core"

urlpatterns = [
    path('', home, name="home"),
    path('checkout', CheckoutView.as_view(), name="checkout"),
    path('order-summary', OrderSummaryView.as_view(), name="order-summary"),
    path('product/<slug>/', ItemDetailView.as_view(), name="product"),
    path('add-to-cart/<slug>/', add_to_cart, name="add-to-cart"),
    path('add-coupon/', AddCouponView.as_view(), name="add-coupon"),
    path('remove-from-cart/<slug>/', remove_from_cart, name="remove-from-cart"),
    path('remove-item-from-cart/<slug>/',remove_single_item_from_cart, name="remove-single-item-from-cart"),
    path('payment/<payment_option>/', PaymentView.as_view(), name="payment"),
    path('category/<id>',category_profile, name="category_profile"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">  
    <title>{% block head_title %}Mishqa's{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <style type="text/css">
        html,
        body,
        header,
        .carousel {
        height: 60vh;
        }
    
        @media (max-width: 740px) {
    
        html,
        body,
        header,
        .carousel {
            height: 100vh;
        }
        }
    
        @media (min-width: 800px) and (max-width: 850px) {
    
        html,
        body,
        header,
        .carousel {
            height: 100vh;
        }
        }
    
    </style>
</head>
{% include "navbar.html" %}

<body>
    <div>

   <div class="mt-5 pt-4">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
   
    {% endif %}

   </div>
   
    
    {% block content  %}

    {% block extra_body %}
    {% endblock %}
    
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
    
    <script type="text/javascript">
       
        new WOW().init();

    </script>
    
    {% endblock content %}
    {% include "footer.html" %}
</body>
</html>

templates/category_profile.html
{% extends "base.html" %}

{% block content %}
<head>
    <style>
        .imageBox{
            position: relative;
            margin: 10px auto;
            border-radius: 4px;
            overflow: hidden;
            max-width: 300px;
            max-height: 300px;
        }
        .imageBox img{
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            
        }

        .imageBox h3{
            position: absolute;
            margin: 0;
            padding: 0;
           
            transform: translateY(50px);
            text-align: center;
            width: 100%;
            font-weight: bold;
            color: #fff;
            text-shadow: 0 2px 5px rgba(0,0,0,0.5);
            transition: .5s;
        }

        .imageBox:hover{
            opacity: 0.5;
            background-color: bisque;
        }
        
        .imageBox:hover h3{
            top: 50%;
            transform: translateY(-50%);
           
        }
    </style>
        
</head>
<body>
    

    <div class="container">
        <div class="row" id="news_title">
            <div class="col-md-12">
                <h1 >{{ one_category.title }}</h1>
            </div>
        </div> 
        <div id="content" class="main_content">  
        <div class="info">
        <div class="row">
            <div class="col-md-11">
                
                <div class="row">
                   
                        {% for post in queryset %}
                        <div class="col-md-4">
                            
                            <div class="imageBox card">
                                <a href="{{ post.get_absoulute_url }}">
                                <img src="{{ post.image.url }}" class="card-img img-fluid">
                                <h3 class="card-body">{{  post.title }}</h3>
                                </a>
                                
                                
                            </div>
                            
                        </div>
                        {% endfor %}

                    
                </div>

            </div>
            <div class="col-md-1"></div>
           
        </div>
    </div>
    </div>
    </div>


</body>
{% endblock %}

templates/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}




<body class="grey lighten-3">

  <!--Main layout-->
  <main>
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Checkout form</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8 mb-4">

          <!--Card-->
          <div class="card">

            <!-- <form>
              {% csrf_token %}
              {{ form|crispy }}
              <button class="btn btn-primary" type="submit">Checkout</button>
            </form> -->

            <!--Card content-->
            <form method="POST" class="card-body">
              {% csrf_token %}
              <!--address-->
              <div class="md-form mb-5">
                <!-- <input type="text" id="address" class="form-control"> -->
                {{ form.street_address }}
                <label for="address" class="">Address</label>
              </div>
              

              <!--address-2-->
              <div class="md-form mb-5">
                <!-- <input type="text" id="address-2" class="form-control"> -->
                {{ form.apartment_address }}
                <label for="address-2" class="">Apartment, suite, etc (optional)</label>
              </div>

              <!--Grid row-->
              <div class="row">

                <!--Grid column-->
                <div class="col-lg-4 col-md-12 mb-4">

                  <label for="country">Country</label>
                  <!-- <select class="custom-select d-block w-100" id="country" required>
                    <option value="">Choose...</option>
                    <option>United States</option>
                  </select> -->
                  {{ form.country }}
                  <div class="invalid-feedback">
                    Please select a valid country.
                  </div>

                </div>
               
                <div class="col-lg-4 col-md-6 mb-4">

                  <label for="zip">Zip</label>
                  <!-- <input type="text" class="form-control" id="zip" placeholder="" required> -->
                  {{ form.zip }}
                  <div class="invalid-feedback">
                    Zip code required.
                  </div>

                </div>
                <!--Grid column-->

              </div>
              <!--Grid row-->

              

              <!-- <div class="md-form mb-5">
                <input type="text" id="phone" class="form-control">
                <label for="phone" class="">Phone (optional)</label>
              </div> -->
              <div class="custom-control custom-checkbox">
                <input {% if form.same_shipping_address.value %}checked{% endif %} type="checkbox" class="custom-control-input" name="same_billing_address" id="same-address">
                <label class="custom-control-label" for="same-address">Shipping address is the same as my billing address</label>
              </div>
              <div class="custom-control custom-checkbox">
                <input {% if form.save_info.value %}checked{% endif %} type="checkbox" class="custom-control-input" name="save_info" id="save-info">
                <label class="custom-control-label" for="save-info">Save this information for next time</label>
              </div>

              <hr>

              <div class="d-block my-3">
                {% for value, name in form.fields.payment_option.choices %}
                <div class="custom-control custom-radio">
                  <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                </div>
                {% endfor %}
               
              </div>
             
              
              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

            </form>

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-4 mb-4">

            {% include "order_snippet.html" %}

         

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

  

</body>

{% endblock %}

templates/footer.html
  
  {% load static %}
  <head>
      <style>
        footer{
          overflow-x: hidden;
          height: 17vh;
          bottom:0;
          text-transform:uppercase;
        }

        #footer-plane{
          left:0;
        }
       
       
        .page-footer ul{
          display: flex;
          list-style: none;
          width: 100%;
        }
        .page-footer ul li{
          margin-left:30px;
          align-items: center;
          text-align: center;
        }

        .page-footer a i{
          right: 0;
          align-items: center;
          text-align: center;
        }

        
        @media screen and (max-width:1024px) and (max-height:1366px){
         footer{
           height: 11vh;
         }
         .page-footer a i{
          right: 40px;
         }
         
         .page-footer ul li{
          margin-left:15px;
          }
         .page-footer a i{
          right: 20px;
         }
        
        }
        @media screen and (max-width:768px) and (max-height:1024px){
          footer{
           height: 11vh;
         }
          
          .page-footer ul li{
          margin-left:10px;
          }
          .page-footer a i{
          right: 40px;
          }
         
          
          
        }
        @media screen and (max-width:500px){
          footer{
            height: 35vh;
            align-items: center;
            text-align:center;
            }
            
            .page-footer ul{
              display: flex;
              flex-direction: column;
              align-items: center;
              text-align:center;
            }
            .page-footer ul li{
              margin-right:60px;
              margin-bottom: 0px;
            }
            .page-footer a i{
              right: 0px;
              margin-top:0;
            }
        }
        @media screen and (max-width:320px){
          footer{
            height: 35vh;
            align-items: center;
            text-align:center;
            font-size: 13px;
          }
          
        }
       
      </style>

  </head>
 <body>

 
  <footer class="page-footer row" style="background-color: rgb(82, 75, 75);">

    
   
  
    <div class="col-md-3 col-sm-3" id="footer-plane">
        <img src="{% static 'img/paperplanes.png' %}" style="height: 50px; width: 50px;left:0">

    </div>
    
    <div class="col-md-6 col-sm-6" id="footer-desk">
      <ul>
        <li>Account</li>
        <li>Privacy Policy</li>
        <li>Terms of Use</li>
        <li>Customer support</li>
      </ul>
          
    </div>
    <div class="col-md-3 col-sm-3" id="footer-media">
        <a href="">
          <i class="fab fa-facebook-f mr-2"></i>
        </a>
  
        <a href="">
          <i class="fab fa-twitter mr-2"></i>
        </a>

        <a href="">
          <i class="fab fa-instagram mr-2"></i>
        </a>
      </div>
    <div class="col-md-12 col-sm-12">
      <h5> Greatness is a process.</h5>
    </div>
   
   

    
  

  </footer>
  <!--/.Footer-->
</body>

templates/item_list.html
{% extends "base.html" %}

{% block content %}

<h2> Here is a list of items.</h2>

{% for item in items %}
 {{ item }}
{% endfor %}
{% endblock %}

templates/navbar.html
{% load cart_template_tags %}
{% load static %}

<head>
  <style>
    nav{display: flex; align-items: center;text-align:center;height: 9vh;}
    .side-nav{ text-transform:uppercase;height:100%;width:0;position:fixed;z-index:1;top:35px;left:0;background-color:#fff;opacity:1.5;overflow-x:hidden;padding-top:60px; transition:0.5s;}
    .side-nav a{padding:10px 10px 10px 30px;text-decoration:none;font-size:22px;color:black;display:block;transition:0.3s;text-align:center;}
    .side-nav a:hover{color:black;}
    .side-nav .btn-close{position:absolute;top:0;font-size:36px}
    #left-nav{position:fixed;z-index:1;top:15px;right:0px;}
    .burger{display:none}
    #Paperplanes img{height: 50px; width: 50px;}
    @media screen and (max-width:1024px) and (max-height:1366px){
      nav{height: 5vh;}
    }
    @media screen and (max-width:768px) and (max-height:1024px){
      nav{height: 6vh;}
      nav .open-slide{top:5px}
      
      .navbar-nav{right:0;}
      #left-nav{position:fixed;z-index:1;top:15px;right:0px;}
      #Paperplanes{margin-left: -700px;}
    }
    @media screen and (max-width:500px){
      /* nav{height:8vh;}
      #nav-headline{display:none}
      #left-nav{position: relative;z-index:1;top:-85px;right:-230px;} */
      nav{height:10vh}
      /* .open-slide{display: none;} */
      .burger{display:none; cursor:pointer;}
      .burger div{width:25px;height: 5px; background-color:black; margin: 3px; top:0;}
      #nav-headline{top:0;}
      #Paperplanes{margin:0;top:-35px;}
      #Paperplanes img{height: 40px; width: 40px;}
      .navbar-nav{position: relative;z-index:1;top:5px;right:-250px }
      .side-nav{ position:absolute; left: 0;height: 92vh; top: 8vh; background-color: #fff; display:flex; flex-direction: column; width: 50%; transform: translateX(-100%);}
      .side-nav a{ opacity: 0;}
      .side-nav-active{transform: translateX(0%);transition: transform 0.5s ease-in;}
       @keyframes navLinkFade{
         from{ opacity:0; transform:translateX(50px);}
         to{opacity: 1; transform:translateX(0px);}
       }
    }
    @media screen and (max-width:320px){
      nav{height:12vh}
      #nav-headline{font-size: 12px;}
      #Paperplanes img{height: 40px; width: 40px;}
      .navbar-nav{right:-220px}
    }
  </style>

</head>
<body>


<!-- Navbar -->
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar row">
       
          <span class="open-slide">
            <a href="#" onclick="openSlideMenu()">
              <svg width="30" height="30">
                  <path d="M0,5 30,5" stroke="#000" stroke-width="5"/>
                  <path d="M0,14 30,14" stroke="#000" stroke-width="5"/>
                  <path d="M0,23 30,23" stroke="#000" stroke-width="5"/>
              </svg>
            </a>
          </span>
        

          <div class="col-md-4 col-sm-12">
              <h6 id="nav-headline">FREE SHIPPING ON ORDERS OVER $75</h6>
          </div>
          <div class="burger" onclick="navSlide()">
            <div class="line1"></div>
            <div class="line2"></div>
            <div class="line3"></div>
          </div>
         
          <div class="col-md-3 col-sm-6" style="justify-content: center; align-items: center;" id="Paperplanes">
            <a href="/">
                <img src="{% static 'img/paperplanes.png' %}">
            </a>  
            
          </div>
          <div class="col-md-1"></div>
          <div class="col-md-4 col-sm-6" id="left-nav">
              <ul class="navbar-nav nav-flex-icons">
                  {% if request.user.is_authenticated %}
                  <li class="nav-item">
                      <a href="" class="nav-link waves-effect">
                        <span class="clearfix d-none d-sm-inline-block"> {{ request.user.username }} </span>
                      </a>
                    </li>
                  <li class="nav-item">
                    <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
                      <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
                      <i class="fas fa-shopping-cart"></i>
                      <span class="clearfix d-none d-sm-inline-block"> Cart </span>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link waves-effect" href="{% url 'account_logout' %}"> 
                      <span class="clearfix d-none d-sm-inline-block"> Logout </span>
                    </a>
                  </li>
                 {% else %}
                 <li class="nav-item">
                    <a class="nav-link waves-effect" href="{% url 'account_login' %}"> 
                      <span class="clearfix d-none d-sm-inline-block"> Login </span>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link waves-effect" href="{% url 'account_signup' %}"> 
                      <span class="clearfix d-none d-sm-inline-block"> Signup </span>
                    </a>
                  </li>
                  {% endif %}
                </ul>
          </div>
       
         
        <!-- Left -->
       

        <!-- Right -->
       

      

    </div>
  </nav>
  <!-- Navbar -->
  <div id="side-menu" class="side-nav">
     
      
      <a href="#" class="btn-close" onclick="closeSlideMenu()">&times;</a>
      <a href="/category/4">New Arrivals</a>
      <a href="/category/1">Hats</a>
      <a href="/category/2">Tees</a>
      <a href="/category/3">Tops</a>
      <a href="#">Bottoms</a>
      <a href="#">Accessories</a>
      <a href="#">Support</a>
    </div>

  <script>
      const navSlide = () => {
        const burger = document.querySelector('.burger');
        const nav = document.querySelector('.side-nav');
        const navLinks = document.querySelectorAll('.side-nav a');
        
        burger.addEventListener('click', () => {
          nav.classList.toggle('side-nav-active');
        });

        navLinks.forEach((link, index) => {
          link.style.animation = 'navLinkFade 0.5s ease forwards ${index/7+0.3}s';
         
        });
      }

      navSlide();

      function openSlideMenu(){
        document.getElementById('side-menu').style.width = '250px';
        document.getElementById('main').style.marginLeft = '250px';
       
      }
  
      function closeSlideMenu(){
        document.getElementById('side-menu').style.width = '0';
        document.getElementById('main').style.marginLeft = '0';
      }

      
    </script>
    </body>

templates/order_snippet.html
<div class="col-md-12 mb-4">

        <!-- Heading -->
        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="text-muted">Your cart</span>
          <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
        </h4>

        <!-- Cart -->
        <ul class="list-group mb-3 z-depth-1">
           {% for order_item in order.items.all %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
              <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title }}</h6>
              <small class="text-muted">{{ order_item.item.description }}</small>
            </div>
            <span class="text-muted">${{ order_item.get_final_price}}</span>
          </li>
         {% endfor %}
          <li class="list-group-item d-flex justify-content-between bg-light">
            <div class="text-success">
              <h6 class="my-0">Promo code</h6>
              <small>{{ order.coupon.code }}</small>
            </div>
            <span class="text-success">-${{ order.coupon.amount }}</span>
          </li>
          <li class="list-group-item d-flex justify-content-between">
            <span>Total (USD)</span>
            <strong>${{ order.get_total }}</strong>
          </li>
        </ul>
        <!-- Cart -->

         <!-- Promo code -->
         {% if DISPLAY_COUPON_FORM %}
         <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
             {% csrf_token %}
            <div class="input-group">
                <!-- <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2"> -->
                {{ couponform.code }}
                <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
                </div>
            </div>
        </form>
        {% endif %}
              <!-- Promo code -->

       

</div>

templates/order_summary.html
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
  <style>
    .table-responsive{
      overflow-x: auto;
    }
    table{
      border-collapse: collapse;
    }
    .btn{
      float:right;
    }
    #checkout {
      margin-left: 10px;
    }
    @media screen and (max-width:500px){
      table{
        width: 100%;
      }
      .btn {
        float: left;
      }
      #checkout {
       margin-left: 0px;
       margin-bottom: 10px;
     }
    }
  </style>
  
</head>


<body>

  <!--Main layout-->
  <main>
    <div class="container">
            <div class="table-responsive text-nowrap">
                    <h2> Order Summary</h2>
                    <table class="table">
                      <thead>
                        <tr>
                          <th scope="col">#</th>
                          <th scope="col">Item title</th>
                          <th scope="col">Price</th>
                          <th scope="col">Quantity</th>
                          <th scope="col">Total Item Price</th>
                          
                         
                        </tr>
                      </thead>
                      <tbody>
                          {% for order_item in object.items.all %}
                        <tr>
                          <th scope="row">{{ forloop.counter }}</th>
                          <td>{{ order_item.item.title }}</td>
                          <td>{{ order_item.item.price }}</td>
                          <td>
                                <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus ml-2"></i></a>
                                {{ order_item.quantity }}
                                <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
                          </td>
                          <td>
                              {% if order_item.item.discount_price %}
                                {{ order_item.get_total_discount_item_price }}
                                <span class="badge badge-primary">Saving ${{ order_item.get_amount_saved }}</span>
                                {% else %}
                                {{ order_item.get_total_item_price }}
                              {% endif %}
                                <a style="color:red" href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                                    <i class="fas fa-trash float-right"></i>
                                </a>
                          <td>
                          
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="5">Your cart is empty</td>
                        </tr>
                        <tr>
                            <td colspan="5">
                                <a class="btn btn-primary float-right" href="/" >Continue shopping</a>
                            </td>
                            
                        </tr>
                         {% endfor %}
                         {% if object.coupon %}
                         <tr>
                            <td colspan="4"><b>Coupon</b></td>
                            <td><b>-${{ object.coupon.amount }}</b></td>
                        </tr>
                         {% endif %}
                         {% if object.get_total %}
                        <tr>
                            <td colspan="4"><b>Order Total</b></td>
                            <td><b>{{ object.get_total }}</b></td>
                        </tr>
                        <tr>
                            <td colspan="5">
                                <a class="btn btn-warning" id="checkout" href="/checkout" >Proceed to checkout</a>
                                <a class="btn btn-primary" href="/" >Continue shopping</a>
                            </td>
                           
                        </tr>
                        {% endif %}
                      </tbody>
                    </table>
                  
                  </div>
      
    </div>
  </main>
  <!--Main layout-->


</body>

</html>
{% endblock %}

templates/product.html
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<head>
  <style>
    .product{
      height: 550px;
      width: 450px;
    }
    @media screen and (min-width:768px){
      .product{
      height: 450px;
      width: 350px;
     }
    }
    @media screen and (max-width:500px){
      .product{
      height: 400px;
      width: 300px;
     }
    }
  </style>
</head>
<body>

  <!--Main layout-->
  <main class="mt-1 pt-1">
    <div class="container dark-grey-text ">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">
          <div class="card product">
            <img src="{{ object.image.url }}" class="img-fluid card-img-top" alt="{{ object.title }}">
          </div>
          

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                {% for cat in  object.categories.all %}
                <span class="badge purple mr-1">{{ cat }}</span>
                {% endfor %}
              </a>
             
            </div>

            <p class="lead">
              {% if object.discount_price %}
              <span class="mr-1">
                <del>${{ object.price }}</del>
              </span>
              <span>${{ object.discount_price }}</span>
              {% else %}
              <span>${{ object.price }}</span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{ object.description }}</p>

            <!-- <form class="d-flex justify-content-left">
             
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> -->

            <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p mt-1">Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p mt-1" id="remove_from_cart">Remove from cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>


          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

     

    </div>
  </main>
  <!--Main layout-->

  
</body>



{% endblock %}

templates/profile.html
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>

<body>

  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">
      
        <div class="col-md-6 mb-4">
                {{ object.order.items }}
                {{ object.order.start_date }}
                <!--Grid column-->
                
      

        </div>
        <!--Grid column-->

        

      </div>
      <!--Grid row-->

      <hr>

     

    </div>
  </main>
  <!--Main layout-->

  
</body>



{% endblock %}